### ISSUE TITLE
Error in new version Deno 1.2.0

### ISSUE THREAD

**Issue by aghussb** [denjucks/dex#6]
![image](https://user-images.githubusercontent.com/50224384/87636851-8d0ba480-c76b-11ea-9028-57574d5e89ac.png)

**Comment by eveningkid** [comment]
Hello @denjucks,

I got a few users complaining about the same issue with denodb (https://github.com/eveningkid/denodb/issues/77, https://github.com/eveningkid/denodb/issues/78).

This seems a very little issue that breaks it all (maybe just replace `URL | string` with `string` only?).

Do you have any idea if this could be solved?

Thanks for your time!

**Comment by aghussb** [comment]
I have already fix it waiting for pull requests merge from @denjucks

**Comment by eveningkid** [comment]
@denjucks, could you please help with this?

Many people are stuck because of it and to my knowledge this should be easy to solve.

Thank you.

**Comment by sant123** [comment]
https://github.com/denjucks/dex/pull/7

**Comment by SquareMesh** [comment]
@denjucks @marckent04 as per others above, issue is still occurring, even though a fix related to this has been undertaken.

I'm importing library using..

`import Dex from "https://deno.land/x/dex/mod.ts"; 
`

**Comment by marckent04** [comment]
yes yes when i import Dex also i have the same error

**Comment by hackers267** [comment]
@denjucks 
I noticed that the code  was modified, but it was not distribute executable code to https://deno.land/x/dex/

**Comment by biggledfred** [comment]
Just a nudge to see whether we can distribute these changes as executable code to deno.land please?

**Comment by biggledfred** [comment]
So it looks like Denjuks activity has gone quiet in August, firstly I hope you are Okay @denjucks? Is there anything we can do to help support this repo, and speed up changes/releases? This is a blocker for using DenoDb at the moment :-(

**Comment by marckent04** [comment]
yes yes everything is blocked. I even tried to dig into the code to
understand and that's when I realized that it was purely js and the node
libraries were imported but since they were imported into the standard
libraries from Deno isn't it better to use them directly first?

Le sam. 8 août 2020 à 06:32, biggledfred <notifications@github.com> a
écrit :

**Comment by SquareMesh** [comment]
Hi @marckent04,

Current version in GitHub when download outside of Deno works.  Thanks for merging fix and commit to github.  

Are you able to update Deno Land?  

This will allow other Deno land libraries to work without downloading local copy.  Let us know if this can be done or if others can assist you with this?

**Comment by marckent04** [comment]
Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
this error is reappars

**Comment by hackers267** [comment]
@marckent04 If you use the
` import Dex from "https://raw.githubusercontent.com/denjucks/dex/master/mod.ts"`
rather than
` import Dex from "https://deno.land/x/dex/mod.ts";`
the error will be gone.

**Comment by marckent04** [comment]
ok ok thanks

**Comment by marckent04** [comment]
Regarding the problem with jspm I volunteer to get started but really I
need to be clarified on the subject
This issue is causing a big problem right now

**Comment by eveningkid** [comment]
Actually, all needs to be done is to add the package to deno.land **again**.

They changed their process in updating new releases on their website, which now uses Github web hooks.

Just follow the steps here if you have admin access to this repo: http://deno.land/x#add

Then all you need to do is make another release and it will then be added to deno.land.

**Comment by VijalPatel** [comment]
Hello, Anyone found solutions for this.

I am also facing same issue

-------------------------------------------------

error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/x/dex@1.0.2/lib/deps/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/x/dex@1.0.2/lib/deps/path/posix.ts:433:18

Found 2 errors.

-------------------------------------------------

Thanks.
